# Generated by Django 4.2.11 on 2024-03-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nickname', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('age_on_arrival', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animals')),
            ],
        ),
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animaltypes')),
            ],
        ),
        migrations.AddField(
            model_name='animals',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.breeds'),
        ),
        migrations.AddField(
            model_name='animals',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.animals'),
        ),
        migrations.AddConstraint(
            model_name='weighting',
            constraint=models.UniqueConstraint(fields=('animal', 'weight_date'), name='unique_animal_weighting'),
        ),
    ]
