# Generated by Django 4.2.11 on 2024-03-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='nickname',
            new_name='name',
        ),
    ]
